/**
 * fetchDistrictCentroids.mjs
 *
 * Fetches TX congressional, state senate, and state house district centroids
 * from the Census TIGER REST API and regenerates
 * frontend/src/utils/districtCentroids.js
 *
 * Run: node scripts/fetchDistrictCentroids.mjs
 */

import axios from "axios";
import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TIGER = "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Legislative/MapServer";
const http = axios.create({ timeout: 25000 });

async function paginatedQuery(layerId, fields, where = "STATE='48'") {
  const all = [];
  let offset = 0;
  while (true) {
    const res = await http.get(`${TIGER}/${layerId}/query`, {
      params: { where, outFields: fields.join(","), returnGeometry: false, f: "json", resultRecordCount: 200, resultOffset: offset },
    });
    const features = res.data?.features || [];
    all.push(...features);
    if (!res.data?.exceededTransferLimit || features.length === 0) break;
    offset += features.length;
  }
  return all;
}

async function fetchCongressional() {
  console.log("Fetching TX Congressional Districts (layer 0 — 119th Congress)…");
  const features = await paginatedQuery(0, ["CD119", "INTPTLAT", "INTPTLON"]);
  const result = {};
  for (const f of features) {
    const a = f.attributes || {};
    const num = parseInt(a.CD119, 10);
    const lat = parseFloat(a.INTPTLAT);
    const lng = parseFloat(a.INTPTLON);
    if (num && !isNaN(lat) && !isNaN(lng)) {
      result[`TX-${num}`] = [+lat.toFixed(4), +lng.toFixed(4)];
    }
  }
  console.log(`  → ${Object.keys(result).length} congressional districts`);
  return result;
}

async function fetchSenate() {
  console.log("Fetching TX State Senate Districts (layer 1 — 2024 Upper)…");
  const features = await paginatedQuery(1, ["SLDU", "INTPTLAT", "INTPTLON"]);
  const result = {};
  for (const f of features) {
    const a = f.attributes || {};
    const num = parseInt(a.SLDU, 10);
    const lat = parseFloat(a.INTPTLAT);
    const lng = parseFloat(a.INTPTLON);
    if (num && !isNaN(lat) && !isNaN(lng)) {
      result[`SD-${num}`] = [+lat.toFixed(4), +lng.toFixed(4)];
    }
  }
  console.log(`  → ${Object.keys(result).length} state senate districts`);
  return result;
}

async function fetchHouse() {
  console.log("Fetching TX State House Districts (layer 2 — 2024 Lower)…");
  const features = await paginatedQuery(2, ["SLDL", "INTPTLAT", "INTPTLON"]);
  const result = {};
  for (const f of features) {
    const a = f.attributes || {};
    const num = parseInt(a.SLDL, 10);
    const lat = parseFloat(a.INTPTLAT);
    const lng = parseFloat(a.INTPTLON);
    if (num && !isNaN(lat) && !isNaN(lng)) {
      result[`HD-${num}`] = [+lat.toFixed(4), +lng.toFixed(4)];
    }
  }
  console.log(`  → ${Object.keys(result).length} state house districts`);
  return result;
}

function sortByDistrict(entries) {
  return entries.sort(([a], [b]) => {
    const [pa, na] = a.split("-");
    const [pb, nb] = b.split("-");
    if (pa !== pb) return pa.localeCompare(pb);
    return parseInt(na, 10) - parseInt(nb, 10);
  });
}

async function main() {
  console.log("═══════════════════════════════════════════════════");
  console.log(" PolicyMarket — District Centroid Fetcher");
  console.log("═══════════════════════════════════════════════════\n");

  const congressional = await fetchCongressional();
  const senate = await fetchSenate();
  const house = await fetchHouse();

  const all = { ...congressional, ...senate, ...house };
  console.log(`\nTotal centroids: ${Object.keys(all).length}`);

  const cdLines = sortByDistrict(Object.entries(congressional))
    .map(([k, [lat, lng]]) => `  "${k}": [${lat}, ${lng}]`);
  const sdLines = sortByDistrict(Object.entries(senate))
    .map(([k, [lat, lng]]) => `  "${k}": [${lat}, ${lng}]`);
  const hdLines = sortByDistrict(Object.entries(house))
    .map(([k, [lat, lng]]) => `  "${k}": [${lat}, ${lng}]`);

  const output = `// Auto-generated by scripts/fetchDistrictCentroids.mjs
// Source: US Census Bureau TIGER REST API — INTPTLAT/INTPTLON (interior label points)
// Keys match MongoDB candidate.district field exactly (no leading zeros).
// Generated: ${new Date().toISOString().split("T")[0]}

export const DISTRICT_CENTROIDS = {
  // ── Texas Congressional Districts (119th Congress) ────────────────────
  ${cdLines.join(",\n  ")},

  // ── Texas State Senate Districts ──────────────────────────────────────
  ${sdLines.join(",\n  ")},

  // ── Texas State House Districts ───────────────────────────────────────
  ${hdLines.join(",\n  ")},
};

function hashString(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  return hash;
}

/**
 * Get the geographic centroid [lat, lng] for a candidate's district string.
 * Falls back to a deterministic hash-scattered offset around the TX center
 * for unknown/future districts.
 *
 * @param {string} districtStr  e.g. "HD-47", "SD-14", "TX-37"
 * @param {object} fallbackGeo  { lat, lng } to anchor fallback scatter
 */
export function getDistrictCentroid(districtStr, fallbackGeo) {
  if (!districtStr) return fallbackGeo;

  const key = districtStr.toUpperCase().trim();
  if (DISTRICT_CENTROIDS[key]) {
    const [lat, lng] = DISTRICT_CENTROIDS[key];
    return { lat, lng };
  }

  // Deterministic scatter for unknown districts
  const hash = hashString(key);
  const dLat = ((hash % 2000) / 1000) - 1.0;
  const dLng = (((hash >> 4) % 3000) / 1000) - 1.5;
  const baseLat = fallbackGeo?.lat || 31.0;
  const baseLng = fallbackGeo?.lng || -98.5;
  return { lat: baseLat + dLat, lng: baseLng + dLng };
}
`;

  const outPath = resolve(__dirname, "../../frontend/src/utils/districtCentroids.js");
  writeFileSync(outPath, output, "utf8");
  console.log(`✓ Written to ${outPath}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
